version: 2.1

jobs:
  # nonSystemTest-jdk8:
  #
  #   docker:
  #     - image: mdernst/randoop-ubuntu-jdk8
  #
  #   steps:
  #
  #     - restore_cache:
  #         keys:
  #           - source-v2-{{ .Branch }}-{{ .Revision }}
  #           - source-v2-{{ .Branch }}-
  #           - source-v2-
  #     - checkout
  #     - save_cache:
  #         key: source-v2-{{ .Branch }}-{{ .Revision }}
  #         paths:
  #           - ".git"
  #
  #     - restore_cache:
  #         keys:
  #           - gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}
  #           - gradle-v2-{{ .Branch }}-
  #           - gradle-v2-
  #
  #     - run: ./scripts/test-nonSystemTest.sh
  #
  #     - save_cache:
  #         paths:
  #           - ~/.gradle
  #         key: gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}
  #
  # systemTest-jdk8:
  #
  #   docker:
  #     - image: mdernst/randoop-ubuntu-jdk8
  #
  #   steps:
  #
  #     - restore_cache:
  #         keys:
  #           - source-v2-{{ .Branch }}-{{ .Revision }}
  #           - source-v2-{{ .Branch }}-
  #           - source-v2-
  #     - checkout
  #     - save_cache:
  #         key: source-v2-{{ .Branch }}-{{ .Revision }}
  #         paths:
  #           - ".git"
  #
  #     - restore_cache:
  #         keys:
  #           - gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}
  #           - gradle-v2-{{ .Branch }}-
  #           - gradle-v2-
  #
  #     - run:
  #         command: ./scripts/test-systemTest.sh
  #         no_output_timeout: 20m
  #
  #     - save_cache:
  #         paths:
  #           - ~/.gradle
  #         key: gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}

  nonSystemTest-jdk11:

    docker:
      - image: mdernst/randoop-ubuntu-jdk11

    steps:

      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - checkout
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          keys:
            - gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-v2-{{ .Branch }}-
            - gradle-v2-

      - run: ./scripts/test-nonSystemTest.sh

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}

      # From https://circleci.com/docs/2.0/collect-test-data/#gradle-junit-results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  systemTest-jdk11:

    docker:
      - image: mdernst/randoop-ubuntu-jdk11

    steps:

      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - checkout
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          keys:
            - gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-v2-{{ .Branch }}-
            - gradle-v2-

      - run:
          command: ./scripts/test-systemTest.sh
          no_output_timeout: 20m

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}

      # From https://circleci.com/docs/2.0/collect-test-data/#gradle-junit-results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  misc:

    docker:
      - image: mdernst/randoop-ubuntu-jdkany

    steps:

      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - checkout
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          keys:
            - gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-v2-{{ .Branch }}-
            - gradle-v2-

      - run: ./scripts/test-misc.sh

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-v2-{{ .Branch }}-{{ checksum "build.gradle" }}

workflows:
  version: 2
  build:
    jobs:
      # - nonSystemTest-jdk8
      # - systemTest-jdk8
      - nonSystemTest-jdk11
      - systemTest-jdk11
      - misc
